### PR TITLE
get cookie from cookies.sqlite db instead of recovery file

### PR DESCRIPTION
**Pull request by fplust**

### CODE REVIEW

**Comment by flabbergastedbd** [comment]
Thanks for the pull request @fplust. Session cookies are generally in recovery file and not in sqlite db. Don't you think we should be merging results from both places rather than just using sqlite db?

**Comment by jamesredwards** [comment]
Realise this PR is very old, but I've been trying to use this library with no success because it doesn't merge the cookies from both the recovery file and the sqlite db. So I would be in favour of merging. There have been changes to the format of the firefox ini file since 2019 as well, which is probably a separate PR

**Comment by flabbergastedbd** [comment]
@jamesredwards  Incase you work on a PR please send it and I will merge. This PR needs some changes, cannot be merged in current form. I can also transfer the ownership if you want to take over the codebase.

**Comment by jamesredwards** [comment]
thanks, will send a couple. first time PR so bear with me.

**Pull request closed without merging**
