### PR TITLE
Add workflow actions and lint the code

### PR DESCRIPTION
**Pull request by Ginkooo**
Hey, I have this other pull request, I hope you'll find it useful :) @tunnelshade

### CODE REVIEW

**Comment by flabbergastedbd** [comment]
@Ginkooo Would you mind taking the ownership of this repository? I can transfer it over

**Comment by Ginkooo** [comment]
> @Ginkooo Would you mind taking the ownership of this repository? I can transfer it over

Sure, I could maintain that :)

**Comment by flabbergastedbd** [comment]
Do you mind deleting your fork
image

**Comment by Ginkooo** [comment]
> Do you mind deleting your fork
> image
> 

Deleted

**Comment by Ginkooo** [comment]
> @Ginkooo Would you mind taking the ownership of this repository? I can transfer it over

Could you also add me as a owner of the package at crates.io? Here's my profile there: https://crates.io/users/Ginkooo Thanks :)

**Pull request closed without merging**
